name: Github Pages

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Directory that will be published on github pages
      PUBLISH_DIR: ./book/_build/html

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Build docs
        run: make docs

      - name: Install jupyterlite
        run: |
          python3 -m pip install jupyterlite
      - name: Build the JupyterLite site
        run: |
          find book/docs -name '*.md' -exec jupytext --to ipynb {} +
          find book/docs -name '*.md' -delete
          jupyter lite build --contents book/docs/ --output-dir ./book/_build/html/lite

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.PUBLISH_DIR }}
